#!/usr/bin/env ruby

require "rgdev"

args, opt_parser = Rgdev._parse_args(ARGV)

if args.help
  puts opt_parser
elsif args.version
  puts "rgdev #{Rgdev::VERSION}"
elsif args.reset
  Rgdev.reset
elsif args.command
  Rgdev.run(args.command)
end
