#!/usr/bin/env ruby

force_run = ARGV.include?('--force') || ARGV.include?('--yolo')

if File.basename(Dir.pwd) != "rubygems" && !force_run
  $stderr.puts "#{$0}: error: expected to be ran from a directory named \`rubygems'."
  $stderr.puts "Pass --force to attempt anyway."
  exit 1
end

exec 'rake newb'
