#!/usr/bin/env ruby

require "open3"

force_run = ARGV.include?("--force")
ARGV.delete("--force")

if File.basename(Dir.pwd) != "rubygems" && !force_run
  $stderr.puts "#{$0}: error: expected to be ran from a directory named \`rubygems'."
  $stderr.puts "Pass --force to attempt anyway."
  exit 1
end

def docker(cmd)
  workdir = "/home/developer/rubygems"
  volume  = "#{Dir.pwd}:#{workdir}"
  uid     = "-u #{ENV['UID']}" if ENV['UID']

  exec "docker run -h rgdev --rm -it -v #{volume} -w #{workdir} #{uid} duckinator/rubygems-dev #{cmd}"
end

case ARGV[0]
when nil, "-h", "--help"
  puts "Usage:  rgdev [COMMAND]"
else
  docker(ARGV.join(" "))
end
